service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:056712157713:table/usersTable

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package: 
  individually: true
  patterns:
    - "!.dynamodb"

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-user:
    handler: getUsers/handler.getUser
    events:
      - http:
          path: users/{id}
          method: GET
  get-users:
    handler: getUsers/handler.getUsers
    events:
      - http:
          path: users
          method: GET
  get-personajes:
    handler: getPersonajes/handler.getPersonajes
    events:
      - http:
          path: personajes
          method: GET
  create-users:
    handler: createUsers/handler.createUsers
    events:
      - http:
          path: users
          method: POST
  update-users:
    handler: updateUsers/handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    handler: deleteUsers/handler.deleteUsers
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
